id: wordpress-WPEngine-config

info:
  name: Wordpress WPEngine Config Disclosure
  author: rix4uni
  severity: high
  description: This file disclosure API key from WPEngine, DB username, DB password and so on.
  reference:
    - https://twitter.com/abison_binoy/status/1580170805274501120
    - https://infosecwriteups.com/p1-vulnerability-in-60-seconds-85ef93d42b99
    - https://www.acunetix.com/vulnerabilities/web/wpengine-_wpeprivate-config-json-information-disclosure
  metadata:
    google-query:
      - inurl:"_wpeprivate"
    fofa-query:
      - body="_wpeprivate"
  tags: WPEngine-config,wordpress,_wpeprivate,misconfiguration

requests:
  - method: GET
    path:
      - "{{BaseURL}}/_wpeprivate/config.json"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '"WPENGINE_ACCOUNT":'
          - '"WPENGINE_SESSION_DB_USERNAME":'
          - '"WPENGINE_SESSION_DB_PASSWORD":'
          - '"WPENGINE_SESSION_DB_SCHEMA":'
          - '"wpengine_apikey":'
          - '"WP_CACHE_KEY_SALT":'
          
      - type: status
        status:
          - 200