id: swagger-ui-detect

info:
  name: Swagger-ui Detect
  author: rix4uni
  severity: info
  description: description
  reference:
    - https://
  tags: swagger,swagger-ui,detect,technologies

requests:
  - method: GET
    path:
      - "{{BaseURL}}/favicon.ico"
      - "{{BaseURL}}/favicon-16x16.png"
      - "{{BaseURL}}/favicon-32x32.png"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: dsl
        dsl:
          - "status_code==200 && (\"-1128940573\" == mmh3(base64_py(body)))"
          - "status_code==200 && (\"1120729672\" == mmh3(base64_py(body)))"

      - type: status
        status:
          - 200