id: proftpd-config

info:
  name: ProFTPD Configuration File - Detect
  author: sheikhrishad
  severity: info
  description: ProFTPD configuration file was detected.
  reference: http://www.proftpd.org/docs/howto/ConfigFile.html
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: config,exposure,proftpd,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/proftpd.conf"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "ProFTPD"
          - "ServerName"
        condition: and

      - type: status
        status:
          - 200
# digest: 490a0046304402207cc7b17e50d95edb3971756a167fb58906abcfb16e6aaeb509969a2eb5c71e02022058c9796930fadcbfbb4d4ecf9086efdb830955113cb409abbf3a13eebce51126:922c64590222798bb761d5b6d8e72950