id: linux-lfi-mass-scale-automation

info:
  name: Linux LFI Mass Scale Automation Vulnerability Check
  author: rix4uni
  severity: critical
  description: Checks for Local File Inclusion vulnerabilities
  tags: lfi,linux

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    payloads:
      reflection: helpers/wordlists/lfi-payloads.txt

    fuzzing:
      - part: query
        type: replace
        mode: multiple
        fuzz:
          - "{{reflection}}"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: regex
        regex:
          - "root:[x*]:0:0"

      - type: status
        status:
          - 200