id: linux-rce-automation

info:
  name: RCE Vulnerability Check
  author: rix4uni
  severity: critical
  description: Checks for Remote Code Execution vulnerabilities
  tags: rce,linux

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    payloads:
      reflection:
        - "id"

    fuzzing:
      - part: query
        type: replace
        mode: multiple
        fuzz:
          - "{{reflection}}"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: regex
        regex:
          - "uid=\d+\(\w+-?\w*\) gid=\d+\(\w+-?\w*\) groups=\d+\(\w+-?\w*\)"

      - type: status
        status:
          - 200