id: icecast-config

info:
  name: Icecast Config - File Disclosure
  author: DhiyaneshDk
  severity: low
  description: |
    Icecast Config file is exposed.
  reference:
    - https://icecast.org/docs/icecast-trunk/config_file/
  metadata:
    verified: true
    max-request: 1
    fofa-query: body="icecast.xml"
  tags: exposure,icecast,config,files,vuln

http:
  - method: GET
    path:
      - '{{BaseURL}}/icecast.xml'

    matchers:
      - type: dsl
        dsl:
          - 'status_code == 200'
          - 'contains(content_type, "application/xml")'
          - 'contains_all(body, "<hostname>","<fileserve>")'
        condition: and
# digest: 4a0a00473045022100dbb87426dda6ee2d3f06bd2f09a5affba309f38ee05d864c9fa7443b1c8cc740022035f5b3edbc4a9e8705bc273c13e8ad0cfd683496a4c30561a3d30a32e09d36a5:922c64590222798bb761d5b6d8e72950