id: pre-commit-config

info:
  name: Pre-commit Configuration File - Detect
  author: DhiyaneshDk
  severity: info
  description: Pre-commit configuration file was detected.
  reference: https://pre-commit.com/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 2
  tags: exposure,devops,config,cicd,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/.pre-commit-config.yaml"
      - "{{BaseURL}}/pre-commit-config.yaml"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "repos:"
          - "hooks:"
          - "rev:"
        condition: and

      - type: status
        status:
          - 200
# digest: 4a0a0047304502210096f8cc3b50e829183b20b33dc43134dba53c416d3716c494761a5f0447844e76022003a7204f8eb40498942da61f69e0b7aaee0ab915ce824ca4a200a8fc20d43e58:922c64590222798bb761d5b6d8e72950