id: pubspec-config

info:
  name: Pubspec YAML Configuration File - Detect
  author: DhiyaneshDk
  severity: info
  description: Pubspec YAML configuration file was detected.
  reference:
    - https://docs.flutter.dev/development/tools/pubspec
    - https://xeladu.medium.com/the-flutter-pubspec-yaml-in-detail-eee5729d9df7
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 2
    shodan-query: html:"pubspec.yaml"
  tags: exposure,devops,pubsec,config,cicd,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/pubspec.yaml"
      - "{{BaseURL}}/assets/pubspec.yaml"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "version:"
          - "environment:"
          - "dependencies:"
        condition: and

      - type: status
        status:
          - 200
# digest: 4a0a00473045022100ade7b5cb70c4ea7e2ec77925ff3199a6b6240e2709f4ea6cd64ae8e09ada239b02200407f1dc689852fb183fd55115543b7f1fd3f210ad42e0bccd4f9f4912c486ac:922c64590222798bb761d5b6d8e72950