id: prometheus-promtail

info:
  name: Prometheus Promtail - Exposure
  author: irshad ahamed
  severity: medium
  description: |
    Prometheus Promtail is an agent that gathers log data from various sources, such as files or systemd journal.
  reference:
    - https://grafana.com/docs/loki/latest/clients/promtail/
    - https://github.com/grafana/loki/issues/8680
  metadata:
    verified: true
    max-request: 1
    shodan-query: http.favicon.hash:932345713
  tags: misconfig,prometheus,promtail,exposure,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/service-discovery"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '>Promtail</a>'
          - 'https://github.com/grafana/loki'
        condition: and

      - type: status
        status:
          - 200
# digest: 490a004630440220722d378a86e281a58b818deb02a97340ecef0cab2e765fecd6776e58f0594c4c02207e1c7bee6e6521e2cbd9bba65b4b72ae172164b0313c0502591c1ba75c21d19a:922c64590222798bb761d5b6d8e72950