id: magicinfo-config-file

info:
  name: Samsung MagicINFO Configuration File
  author: s4e-io
  severity: info
  description: |
    Detects exposure of Samsung MagicINFO configuration file (/MagicInfo/config.js),and extracts magicInfoFrontEndVersion.
  reference:
    - https://www.samsung.com/de/business/display-solutions/magicinfo/
  metadata:
    vendor: samsung
    product: magicinfo_9_server
    shodan-query: title:"MagicINFO"
    fofa-query: title:"MagicINFO"
  tags: config,exposure,magicinfo,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/MagicInfo/config.js"

    matchers:
      - type: dsl
        dsl:
          - 'contains_all(body, "globalConfig", "MagicINFO", "samsung")'

    extractors:
      - type: regex
        name: magicinfo_version
        group: 1
        part: body
        regex:
          - '"magicInfoFrontEndVersion":\s*"([^"]+)"'
# digest: 4a0a00473045022100f3e541763ba1a0d9633aa2150b95e005c4b0539621174b42299e9bbd5060fdef022026224365c6bb3689592cf5e40eb76278fe45ef167b6bbdb7d554c6467a8b20a5:922c64590222798bb761d5b6d8e72950